url: https://thewholepye.com
baseurl: 

# Site settings
title: TWP Design
slug: TWP 
email: beepye@gmail.com
description: ""


# Team names, titles and social links
people:
- name: Brian Pye
  pic: brian
  position: Designer + Developer
  social:
    - title: dribbble
      url: https://dribble.com/beepye
    - title: github
      url: https://github.com/beepye
    - title: stack-overflow
      url: https://stackoverflow.com/users/1566325/beepye

- name: Ronnie Pye
  pic: ronnie
  position: Social Media + Marketing
  social:
    - title: instagram
      url: https://www.instagram.com/liketheboysname/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 

# Build settings
markdown: kramdown
permalink: pretty